title: Supply Chain Analytics
author: Mateen Majgaonkar
description: Supply Chain Analytics with Modern Data Tools
remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: "default"

# Site Settings
locale: "en-US"
title_separator: "-"
name: "Supply Chain Analytics with Modern Data Tools by Mateen Majgaonkar"
url: "https://mat9501.github.io"
baseurl: ""

# Site Author
author:
  name: "Mateen Majgaonkar"
  bio: "Supply Chain Analytics Professional"
  location: "U.S.A"

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      toc: true
      toc_sticky: true
