
# Site settings
title: Supply Chain Analytics
description: Supply Chain Analytics with Modern Data Tools
author: Your Name
baseurl: ""
url: "https://mat9501.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Author Settings
author:
  name: Your Name
  bio: Supply Chain Analytics Professional
  location: Your Location

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Your Name
      comments: true
